from types import SimpleNamespace

FIELD_GROUPS = [
    SimpleNamespace(
        key="surface",
        label="Surface Fields",
        icon="mdi-layers-outline",
        color="primary",
        state_name="variables_2d",
    ),
    SimpleNamespace(
        key="volume",
        label="Atmospheric Fields",
        icon="mdi-cube-outline",
        color="secondary",
        state_name="variables_3d",
    ),
]

FIELDS_METADATA = {
    "CLDHGH": {
        "dim": 2,
        "name": "CLDHGH",
        "units": "fraction (dimensionless, range [0,1])",
        "description": "Vertically-integrated high cloud fraction (random overlap assumption), covering clouds with cloud-top pressure less than 440 hPa",
    },
    "CLDLOW": {
        "dim": 2,
        "name": "CLDLOW",
        "units": "fraction",
        "description": "Vertically-integrated, random overlap, low cloud amount (cloud top pressure greater than 680 hPa)",
    },
    "CLDMED": {
        "dim": 2,
        "name": "CLDMED",
        "units": "fraction",
        "description": "Vertically-integrated, random overlap, mid-level cloud amount (cloud top pressure between 440 hPa and 680 hPa)",
    },
    "FLNT": {
        "dim": 2,
        "name": "FLNT",
        "units": "W/m²",
        "description": "Net longwave flux at top of model",
    },
    "FSNT": {
        "dim": 2,
        "name": "FSNT",
        "units": "W/m²",
        "description": "Net solar flux at top of model",
    },
    "PRECL": {
        "dim": 2,
        "name": "PRECL",
        "units": "m/s",
        "description": "Large-scale (stable) precipitation rate (liquid + ice)",
    },
    "PRECSC": {
        "dim": 2,
        "name": "PRECSC",
        "units": "m/s",
        "description": "Convective snow rate (water equivalent)",
    },
    "PRECSL": {
        "dim": 2,
        "name": "PRECSL",
        "units": "m/s",
        "description": "Large-scale (stable) snow rate (water equivalent)",
    },
    "cnd01_ALL": {
        "dim": 2,
        "name": "cnd01_ALL",
        "units": "",
        "description": "Metric used to build the conditional sampling mask for the 'cnd01' (ALL) diagnostic package",
    },
    "cnd01_ALL_flag": {
        "dim": 2,
        "name": "cnd01_ALL_flag",
        "units": "",
        "description": "Flag marking which columns/levels satisfy the conditional sampling criterion for the 'cnd01' (ALL) diagnostic package",
    },
    "NUMICE": {
        "dim": 3,
        "name": "NUMICE",
        "units": "1/kg",
        "description": "Grid box averaged cloud ice number concentration",
    },
    "NUMLIQ": {
        "dim": 3,
        "name": "NUMLIQ",
        "units": "1/kg",
        "description": "Grid box averaged cloud liquid droplet number concentration",
    },
    "NUMRAI": {
        "dim": 3,
        "name": "NUMRAI",
        "units": "1/kg",
        "description": "Grid box averaged rain number concentration",
    },
    "NUMSNO": {
        "dim": 3,
        "name": "NUMSNO",
        "units": "1/kg",
        "description": "Grid box averaged snow number concentration",
    },
    "RAINQM": {
        "dim": 3,
        "name": "RAINQM",
        "units": "kg/kg",
        "description": "Grid box averaged rain mixing ratio",
    },
    "RHI": {
        "dim": 3,
        "name": "RHI",
        "units": "%",
        "description": "Relative humidity with respect to ice",
    },
    "RHW": {
        "dim": 3,
        "name": "RHW",
        "units": "%",
        "description": "Relative humidity with respect to liquid water",
    },
    "SNOWQM": {
        "dim": 3,
        "name": "SNOWQM",
        "units": "kg/kg",
        "description": "Grid box averaged snow mixing ratio",
    },
    "cnd01_AIST_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_AIST_ACTDIAG01",
        "units": "fraction",
        "description": "Ice stratiform cloud fraction, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_AIST_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_AIST_ACTDIAG02",
        "units": "fraction",
        "description": "Ice stratiform cloud fraction, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_AIST_RAD": {
        "dim": 3,
        "name": "cnd01_AIST_RAD",
        "units": "fraction",
        "description": "Ice stratiform cloud fraction, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_ALST_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_ALST_ACTDIAG01",
        "units": "fraction",
        "description": "Liquid stratiform cloud fraction, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_ALST_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_ALST_ACTDIAG02",
        "units": "fraction",
        "description": "Liquid stratiform cloud fraction, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_ALST_RAD": {
        "dim": 3,
        "name": "cnd01_ALST_RAD",
        "units": "fraction",
        "description": "Liquid stratiform cloud fraction, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_AST_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_AST_ACTDIAG01",
        "units": "fraction",
        "description": "Stratiform cloud fraction (liquid + ice), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_AST_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_AST_ACTDIAG02",
        "units": "fraction",
        "description": "Stratiform cloud fraction (liquid + ice), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_AST_RAD": {
        "dim": 3,
        "name": "cnd01_AST_RAD",
        "units": "fraction",
        "description": "Stratiform cloud fraction (liquid + ice), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN1_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN1_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 1 (~0.02%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN1_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN1_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 1 (~0.02%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN1_RAD": {
        "dim": 3,
        "name": "cnd01_CCN1_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 1 (~0.02%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN2_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN2_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 2 (~0.05%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN2_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN2_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 2 (~0.05%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN2_RAD": {
        "dim": 3,
        "name": "cnd01_CCN2_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 2 (~0.05%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN3_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN3_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 3 (~0.1%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN3_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN3_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 3 (~0.1%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN3_RAD": {
        "dim": 3,
        "name": "cnd01_CCN3_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 3 (~0.1%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN4_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN4_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 4 (~0.2%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN4_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN4_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 4 (~0.2%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN4_RAD": {
        "dim": 3,
        "name": "cnd01_CCN4_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 4 (~0.2%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN5_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN5_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 5 (~0.5%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN5_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN5_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 5 (~0.5%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN5_RAD": {
        "dim": 3,
        "name": "cnd01_CCN5_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 5 (~0.5%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN6_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CCN6_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 6 (~1.0%), sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN6_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CCN6_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 6 (~1.0%), sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CCN6_RAD": {
        "dim": 3,
        "name": "cnd01_CCN6_RAD",
        "units": "1/cm³",
        "description": "Cloud condensation nuclei concentration at supersaturation bin 6 (~1.0%), as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDMC_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CDMC_ACTDIAG01",
        "units": "kg/kg",
        "description": "Cloud droplet mass mixing ratio, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDMC_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CDMC_ACTDIAG02",
        "units": "kg/kg",
        "description": "Cloud droplet mass mixing ratio, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDMC_RAD": {
        "dim": 3,
        "name": "cnd01_CDMC_RAD",
        "units": "kg/kg",
        "description": "Cloud droplet mass mixing ratio, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDNC_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CDNC_ACTDIAG01",
        "units": "1/cm³",
        "description": "Cloud droplet number concentration, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDNC_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CDNC_ACTDIAG02",
        "units": "1/cm³",
        "description": "Cloud droplet number concentration, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CDNC_RAD": {
        "dim": 3,
        "name": "cnd01_CDNC_RAD",
        "units": "1/cm³",
        "description": "Cloud droplet number concentration, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDICE_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CLDICE_ACTDIAG01",
        "units": "kg/kg",
        "description": "Grid box averaged cloud ice amount, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDICE_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CLDICE_ACTDIAG02",
        "units": "kg/kg",
        "description": "Grid box averaged cloud ice amount, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDICE_RAD": {
        "dim": 3,
        "name": "cnd01_CLDICE_RAD",
        "units": "kg/kg",
        "description": "Grid box averaged cloud ice amount, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDLIQ_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CLDLIQ_ACTDIAG01",
        "units": "kg/kg",
        "description": "Grid box averaged cloud liquid amount, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDLIQ_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CLDLIQ_ACTDIAG02",
        "units": "kg/kg",
        "description": "Grid box averaged cloud liquid amount, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CLDLIQ_RAD": {
        "dim": 3,
        "name": "cnd01_CLDLIQ_RAD",
        "units": "kg/kg",
        "description": "Grid box averaged cloud liquid amount, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CONCLD_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_CONCLD_ACTDIAG01",
        "units": "fraction",
        "description": "Convective cloud fraction, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CONCLD_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_CONCLD_ACTDIAG02",
        "units": "fraction",
        "description": "Convective cloud fraction, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_CONCLD_RAD": {
        "dim": 3,
        "name": "cnd01_CONCLD_RAD",
        "units": "fraction",
        "description": "Convective cloud fraction, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMICE_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_NUMICE_ACTDIAG01",
        "units": "1/kg",
        "description": "Grid box averaged cloud ice number concentration, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMICE_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_NUMICE_ACTDIAG02",
        "units": "1/kg",
        "description": "Grid box averaged cloud ice number concentration, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMICE_RAD": {
        "dim": 3,
        "name": "cnd01_NUMICE_RAD",
        "units": "1/kg",
        "description": "Grid box averaged cloud ice number concentration, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMLIQ_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_NUMLIQ_ACTDIAG01",
        "units": "1/kg",
        "description": "Grid box averaged cloud liquid droplet number concentration, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMLIQ_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_NUMLIQ_ACTDIAG02",
        "units": "1/kg",
        "description": "Grid box averaged cloud liquid droplet number concentration, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_NUMLIQ_RAD": {
        "dim": 3,
        "name": "cnd01_NUMLIQ_RAD",
        "units": "1/kg",
        "description": "Grid box averaged cloud liquid droplet number concentration, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_Q_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_Q_ACTDIAG01",
        "units": "kg/kg",
        "description": "Specific humidity, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_Q_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_Q_ACTDIAG02",
        "units": "kg/kg",
        "description": "Specific humidity, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_Q_RAD": {
        "dim": 3,
        "name": "cnd01_Q_RAD",
        "units": "kg/kg",
        "description": "Specific humidity, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_T_ACTDIAG01": {
        "dim": 3,
        "name": "cnd01_T_ACTDIAG01",
        "units": "K",
        "description": "Air temperature, sampled at the first aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_T_ACTDIAG02": {
        "dim": 3,
        "name": "cnd01_T_ACTDIAG02",
        "units": "K",
        "description": "Air temperature, sampled at the second aerosol-activation diagnostic call, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "cnd01_T_RAD": {
        "dim": 3,
        "name": "cnd01_T_RAD",
        "units": "K",
        "description": "Air temperature, as seen by the radiation scheme, restricted to columns/levels flagged by the 'cnd01' (ALL) conditional sampling mask",
    },
    "TS": {"dim": 2, "name": "TS", "units": "K", "description": "Surface temperature"},
    "PS": {"dim": 2, "name": "PS", "units": "Pa", "description": "Surface pressure"},
    "PSL": {
        "dim": 2,
        "name": "PSL",
        "units": "Pa",
        "description": "Sea level pressure",
    },
    "TREFHT": {
        "dim": 2,
        "name": "TREFHT",
        "units": "K",
        "description": "Reference height (2m) temperature",
    },
    "QREFHT": {
        "dim": 2,
        "name": "QREFHT",
        "units": "kg/kg",
        "description": "Reference height humidity",
    },
    "U10": {"dim": 2, "name": "U10", "units": "m/s", "description": "10m wind speed"},
    "PRECT": {
        "dim": 2,
        "name": "PRECT",
        "units": "m/s",
        "description": "Total precipitation rate",
    },
    "PRECC": {
        "dim": 2,
        "name": "PRECC",
        "units": "m/s",
        "description": "Convective precipitation rate",
    },
    "TMQ": {
        "dim": 2,
        "name": "TMQ",
        "units": "kg/m²",
        "description": "Total precipitable water",
    },
    "CLDTOT": {
        "dim": 2,
        "name": "CLDTOT",
        "units": "fraction",
        "description": "Total cloud fraction",
    },
    "FSNS": {
        "dim": 2,
        "name": "FSNS",
        "units": "W/m²",
        "description": "Net solar flux at surface",
    },
    "FLNS": {
        "dim": 2,
        "name": "FLNS",
        "units": "W/m²",
        "description": "Net longwave flux at surface",
    },
    "LHFLX": {
        "dim": 2,
        "name": "LHFLX",
        "units": "W/m²",
        "description": "Surface latent heat flux",
    },
    "SHFLX": {
        "dim": 2,
        "name": "SHFLX",
        "units": "W/m²",
        "description": "Surface sensible heat flux",
    },
    "TAUX": {
        "dim": 2,
        "name": "TAUX",
        "units": "N/m²",
        "description": "Zonal surface wind stress",
    },
    "TAUY": {
        "dim": 2,
        "name": "TAUY",
        "units": "N/m²",
        "description": "Meridional surface wind stress",
    },
    "T": {
        "dim": 3,
        "name": "T",
        "units": "K",
        "description": "Air temperature on model levels",
    },
    "U": {
        "dim": 3,
        "name": "U",
        "units": "m/s",
        "description": "Zonal wind on model levels",
    },
    "V": {
        "dim": 3,
        "name": "V",
        "units": "m/s",
        "description": "Meridional wind on model levels",
    },
    "Q": {
        "dim": 3,
        "name": "Q",
        "units": "kg/kg",
        "description": "Specific humidity on model levels",
    },
    "RELHUM": {
        "dim": 3,
        "name": "RELHUM",
        "units": "%",
        "description": "Relative humidity on model levels",
    },
    "CLOUD": {
        "dim": 3,
        "name": "CLOUD",
        "units": "fraction",
        "description": "Cloud fraction on model levels",
    },
    "CLDLIQ": {
        "dim": 3,
        "name": "CLDLIQ",
        "units": "kg/kg",
        "description": "Cloud liquid water mixing ratio",
    },
    "CLDICE": {
        "dim": 3,
        "name": "CLDICE",
        "units": "kg/kg",
        "description": "Cloud ice mixing ratio",
    },
    "OMEGA": {
        "dim": 3,
        "name": "OMEGA",
        "units": "Pa/s",
        "description": "Vertical pressure velocity",
    },
    "Z3": {"dim": 3, "name": "Z3", "units": "m", "description": "Geopotential height"},
}

SITES = [
    {
        "title": "Southern Great Plains (SGP)",
        "value": "SGP",
        "lat": 36.607,
        "lon": -97.488,
    },
    {
        "title": "North Slope of Alaska (NSA)",
        "value": "NSA",
        "lat": 71.323,
        "lon": -156.609,
    },
    {
        "title": "Eastern North Atlantic (ENA)",
        "value": "ENA",
        "lat": 39.091,
        "lon": -28.026,
    },
]

SITES_LAT_LON = {site["value"]: (site["lat"], site["lon"]) for site in SITES}


VUETIFY_CONFIG = {
    "theme": {
        "defaultTheme": "siteviewLight",
        "themes": {
            "siteviewLight": {
                "dark": False,
                "colors": {
                    "primary": "#1f6f8b",
                    "secondary": "#7d3c98",
                    "background": "#f4f7f9",
                },
            },
            "siteviewDark": {
                "dark": True,
                "colors": {
                    "primary": "#6fc3e0",
                    "secondary": "#c996e6",
                    "background": "#0f1a20",
                },
            },
        },
    },
}
